# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 543)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.blur = QtWidgets.QPushButton(parent=self.centralwidget)
        self.blur.setMaximumSize(QtCore.QSize(100, 100))
        self.blur.setObjectName("blur")
        self.verticalLayout_4.addWidget(self.blur)
        self.black_white = QtWidgets.QPushButton(parent=self.centralwidget)
        self.black_white.setMaximumSize(QtCore.QSize(100, 100))
        self.black_white.setObjectName("black_white")
        self.verticalLayout_4.addWidget(self.black_white)
        self.enhance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enhance.setMaximumSize(QtCore.QSize(100, 100))
        self.enhance.setObjectName("enhance")
        self.verticalLayout_4.addWidget(self.enhance)
        self.sharpen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sharpen.setMaximumSize(QtCore.QSize(100, 100))
        self.sharpen.setObjectName("sharpen")
        self.verticalLayout_4.addWidget(self.sharpen)
        self.smooth = QtWidgets.QPushButton(parent=self.centralwidget)
        self.smooth.setMaximumSize(QtCore.QSize(100, 100))
        self.smooth.setObjectName("smooth")
        self.verticalLayout_4.addWidget(self.smooth)
        self.emboss = QtWidgets.QPushButton(parent=self.centralwidget)
        self.emboss.setMaximumSize(QtCore.QSize(100, 100))
        self.emboss.setObjectName("emboss")
        self.verticalLayout_4.addWidget(self.emboss)
        self.edge_enhance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edge_enhance.setMaximumSize(QtCore.QSize(100, 100))
        self.edge_enhance.setObjectName("edge_enhance")
        self.verticalLayout_4.addWidget(self.edge_enhance)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.photo_choice_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.photo_choice_button.setObjectName("photo_choice_button")
        self.verticalLayout_6.addWidget(self.photo_choice_button)
        self.image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_6.addWidget(self.image_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.setStretch(1, 5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoEditor"))
        self.blur.setText(_translate("MainWindow", "Blur"))
        self.black_white.setText(_translate("MainWindow", "Black/White"))
        self.enhance.setText(_translate("MainWindow", "Enhance Image"))
        self.sharpen.setText(_translate("MainWindow", "Sharpen"))
        self.smooth.setText(_translate("MainWindow", "Smooth"))
        self.emboss.setText(_translate("MainWindow", "Emboss"))
        self.edge_enhance.setText(_translate("MainWindow", "Edge enhance"))
        self.photo_choice_button.setText(_translate("MainWindow", "Choose your photo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
