# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 499)
        MainWindow.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(68, 68, 68);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.redo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.redo.setMinimumSize(QtCore.QSize(0, 0))
        self.redo.setMaximumSize(QtCore.QSize(35, 35))
        self.redo.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"}")
        self.redo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("redo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.redo.setIcon(icon)
        self.redo.setIconSize(QtCore.QSize(25, 25))
        self.redo.setObjectName("redo")
        self.gridLayout_2.addWidget(self.redo, 1, 1, 1, 1)
        self.undo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.undo.setMinimumSize(QtCore.QSize(0, 0))
        self.undo.setMaximumSize(QtCore.QSize(35, 35))
        self.undo.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"}")
        self.undo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("undo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.undo.setIcon(icon1)
        self.undo.setIconSize(QtCore.QSize(25, 25))
        self.undo.setObjectName("undo")
        self.gridLayout_2.addWidget(self.undo, 1, 0, 1, 1)
        self.save_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_file.setMinimumSize(QtCore.QSize(0, 0))
        self.save_file.setMaximumSize(QtCore.QSize(35, 35))
        self.save_file.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"}")
        self.save_file.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("save.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_file.setIcon(icon2)
        self.save_file.setIconSize(QtCore.QSize(29, 29))
        self.save_file.setObjectName("save_file")
        self.gridLayout_2.addWidget(self.save_file, 0, 1, 1, 1)
        self.open_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_file.setMinimumSize(QtCore.QSize(0, 0))
        self.open_file.setMaximumSize(QtCore.QSize(35, 35))
        self.open_file.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"}")
        self.open_file.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.open_file.setIcon(icon3)
        self.open_file.setIconSize(QtCore.QSize(25, 25))
        self.open_file.setObjectName("open_file")
        self.gridLayout_2.addWidget(self.open_file, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.enhance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enhance.setMinimumSize(QtCore.QSize(92, 0))
        self.enhance.setMaximumSize(QtCore.QSize(115, 30))
        self.enhance.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.enhance.setObjectName("enhance")
        self.verticalLayout_4.addWidget(self.enhance)
        self.blur = QtWidgets.QPushButton(parent=self.centralwidget)
        self.blur.setMinimumSize(QtCore.QSize(92, 0))
        self.blur.setMaximumSize(QtCore.QSize(115, 30))
        self.blur.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.blur.setObjectName("blur")
        self.verticalLayout_4.addWidget(self.blur)
        self.black_white = QtWidgets.QPushButton(parent=self.centralwidget)
        self.black_white.setMinimumSize(QtCore.QSize(92, 0))
        self.black_white.setMaximumSize(QtCore.QSize(115, 30))
        self.black_white.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.black_white.setObjectName("black_white")
        self.verticalLayout_4.addWidget(self.black_white)
        self.sharpen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sharpen.setMinimumSize(QtCore.QSize(92, 0))
        self.sharpen.setMaximumSize(QtCore.QSize(115, 30))
        self.sharpen.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.sharpen.setObjectName("sharpen")
        self.verticalLayout_4.addWidget(self.sharpen)
        self.smooth = QtWidgets.QPushButton(parent=self.centralwidget)
        self.smooth.setMinimumSize(QtCore.QSize(92, 0))
        self.smooth.setMaximumSize(QtCore.QSize(115, 30))
        self.smooth.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.smooth.setObjectName("smooth")
        self.verticalLayout_4.addWidget(self.smooth)
        self.emboss = QtWidgets.QPushButton(parent=self.centralwidget)
        self.emboss.setMinimumSize(QtCore.QSize(92, 0))
        self.emboss.setMaximumSize(QtCore.QSize(115, 30))
        self.emboss.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.emboss.setObjectName("emboss")
        self.verticalLayout_4.addWidget(self.emboss)
        self.edge_enhance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edge_enhance.setMinimumSize(QtCore.QSize(92, 0))
        self.edge_enhance.setMaximumSize(QtCore.QSize(115, 30))
        self.edge_enhance.setStyleSheet("QPushButton {\n"
"    color: #CACACA;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"    border-color: #888888;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"    background-color: #444444;\n"
"    min-width: 80px;\n"
"}")
        self.edge_enhance.setObjectName("edge_enhance")
        self.verticalLayout_4.addWidget(self.edge_enhance)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_6.addWidget(self.image_label)
        self.effect_slider = QtWidgets.QSlider(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect_slider.sizePolicy().hasHeightForWidth())
        self.effect_slider.setSizePolicy(sizePolicy)
        self.effect_slider.setMinimumSize(QtCore.QSize(400, 0))
        self.effect_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.effect_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 10px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    background: red;\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: green;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: pink;\n"
"}")
        self.effect_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.effect_slider.setObjectName("effect_slider")
        self.verticalLayout_6.addWidget(self.effect_slider, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.setStretch(1, 5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoEditor"))
        self.enhance.setText(_translate("MainWindow", "Enhance Image"))
        self.blur.setText(_translate("MainWindow", "Blur"))
        self.black_white.setText(_translate("MainWindow", "Black/White"))
        self.sharpen.setText(_translate("MainWindow", "Sharpen"))
        self.smooth.setText(_translate("MainWindow", "Smooth"))
        self.emboss.setText(_translate("MainWindow", "Emboss"))
        self.edge_enhance.setText(_translate("MainWindow", "Edge enhance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
